In [16]:
import numpy as np

In [17]:
import pandas as pd

from scipy.stats import mode

import warnings
warnings.filterwarnings('ignore')

##### Задание 1
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. 
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. 

Будем считать, что каждый столбец - это признак, а строка - наблюдение. З
атем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. 
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [18]:
a = np.array ([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])
print(a)

print("Среднее значение")

mean_a = (a.mean(axis=0))
print(mean_a)


[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Среднее значение
[2.  8.4]


##### Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, 
содержащиеся в массиве mean_a. 
Вычисление должно производиться в одно действие. 
Получившийся массив должен иметь размер 5x2.

In [19]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


#### Задание 3
Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [20]:
a_centered_t = a_centered.T
a_centered_sp = (a_centered.dot(a_centered_t) / 4)

print(a_centered_sp)


[[ 1.69  0.24 -1.81 -1.21  1.09]
 [ 0.24  0.04 -0.26 -0.16  0.14]
 [-1.81 -0.26  1.94  1.29 -1.16]
 [-1.21 -0.16  1.29  0.89 -0.81]
 [ 1.09  0.14 -1.16 -0.81  0.74]]


## Тема “Работа с данными в Pandas”

#### Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. 
Создайте датафрейм authors со столбцами author_id и author_name, 
в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, 
в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']








In [27]:
import pandas as pd

authors = {
   "author_id":[1, 2, 3],
    "author_name":['Тургенев', 'Чехов', 'Островский']
}

a = pd.DataFrame(authors)

book = {
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 
                 'Дворянское гнездо', 
                 'Толстый и тонкий', 
                 'Дама с собачкой', 
                 'Гроза', 
                 'Таланты и поклонники'],
    "price": [100,150,200,300,400,500,600]
}
b = pd.DataFrame(book)

b




author_id            book_title  price
0          1           Отцы и дети    100
1          1                 Рудин    150
2          1     Дворянское гнездо    200
3          2      Толстый и тонкий    300
4          2       Дама с собачкой    400
5          3                 Гроза    500
6          3  Таланты и поклонники    600

### Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [116]:
authors = {
   "author_id":[1, 2, 3],
    "author_name":['Тургенев', 'Чехов', 'Островский']
}

a = pd.DataFrame(authors)

book = {
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 
                 'Дворянское гнездо', 
                 'Толстый и тонкий', 
                 'Дама с собачкой', 
                 'Гроза', 
                 'Таланты и поклонники'],
    "price": [100,150,200,300,400,500,600]
}
b = pd.DataFrame(book)

authors_price = pd.merge(a,b,on='author_id', how='inner' )

authors_price


author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    100
1          1    Тургенев                 Рудин    150
2          1    Тургенев     Дворянское гнездо    200
3          2       Чехов      Толстый и тонкий    300
4          2       Чехов       Дама с собачкой    400
5          3  Островский                 Гроза    500
6          3  Островский  Таланты и поклонники    600

### Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [38]:
top5 = authors_price.nlargest(5,'price')
top5

author_id author_name            book_title  price
6          3  Островский  Таланты и поклонники    600
5          3  Островский                 Гроза    500
4          2       Чехов       Дама с собачкой    400
3          2       Чехов      Толстый и тонкий    300
2          1    Тургенев     Дворянское гнездо    200

### Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price. 
В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора,
минимальная, максимальная и средняя цена на книги этого автора.

In [195]:
authors_stat = authors_price.groupby('author_name')
authors_stat.agg(
 min_price = ('price','min'),
   max_price = ('price','max'),
   mean_price = ('price','mean')
)

min_price  max_price  mean_price
author_name                                  
Островский         500        600       550.0
Тургенев           100        200       150.0
Чехов              300        400       350.0